// Top 10 Dubai Restaurants — Real menus with actual prices in AED
export const dubaiRestaurants = [
  {
    name: "Zuma",
    slug: "zuma-dubai",
    cuisineType: "Japanese",
    description: "Contemporary Japanese cuisine in an izakaya-style setting. Located in the heart of DIFC, Zuma has been a Dubai icon since opening, blending traditional Japanese flavors with modern flair across its sushi counter, robata grill, and main kitchen.",
    address: "Gate Village, Building 3, DIFC, Dubai",
    menuName: "A La Carte Menu",
    menuDescription: "Modern Japanese sharing plates — sushi, sashimi, robata grill & signature dishes",
    items: [
      { name: "Spicy Beef Tenderloin", description: "Premium beef tenderloin with sesame, red chili and sweet soy", price: "285", category: "Signature Dishes", isBestseller: true },
      { name: "Black Cod with Miso", description: "Marinated in sweet den miso and baked until silky soft", price: "350", category: "Signature Dishes", isChefsPick: true },
      { name: "Lamb Cutlets with Korean Spices", description: "Tender lamb with aromatic Korean-inspired seasonings from the robata grill", price: "320", category: "Signature Dishes" },
      { name: "Salmon Teriyaki", description: "Atlantic salmon with pickled cucumber and Zuma's signature teriyaki glaze", price: "174", category: "From the Robata Grill" },
      { name: "Grilled Wagyu Sirloin", description: "Premium wagyu with ponzu and truffle", price: "285", category: "From the Robata Grill", isChefsPick: true },
      { name: "Rock Shrimp Tempura", description: "Crispy tempura rock shrimp with spicy mayo and yuzu", price: "133", category: "Tempura" },
      { name: "Lobster Tempura", description: "Grilled lobster tempura with spicy ponzu mayo", price: "312", category: "Tempura" },
      { name: "Tuna Sashimi", description: "Premium akami tuna, thinly sliced", price: "76", category: "Sushi & Sashimi" },
      { name: "Yellowtail with Jalapeño", description: "Buttery yellowtail sashimi with jalapeño and ponzu", price: "55", category: "Sushi & Sashimi", isBestseller: true },
      { name: "Sea Bass with Yuzu", description: "Delicate white fish with citrus yuzu notes", price: "45", category: "Sushi & Sashimi" },
      { name: "Spicy Tuna Roll", description: "Tuna with spicy miso and yuzu tobiko", price: "95", category: "Maki Rolls" },
      { name: "California Maki", description: "Fresh lobster, avocado and tobiko", price: "105", category: "Maki Rolls" },
      { name: "Dynamite Spider Roll", description: "Soft-shell crab, spicy mayo, cucumber and wasabi tobiko", price: "114", category: "Maki Rolls" },
      { name: "Zuma Salad", description: "Mixed greens with ginger-miso dressing", price: "69", category: "Salads" },
      { name: "Green Salad", description: "Avocado and asparagus with lemon-honey dressing", price: "78", category: "Salads" },
      { name: "Steamed Japanese Spinach", description: "With toasted sesame", price: "68", category: "Sides" },
    ],
  },
  {
    name: "Nobu",
    slug: "nobu-dubai",
    cuisineType: "Japanese-Peruvian",
    description: "Celebrity Chef Nobu Matsuhisa's iconic restaurant at Atlantis, The Palm. Cutting-edge Japanese cuisine fused with Peruvian influences, set against stunning views of The Palm and the Arabian Gulf.",
    address: "Atlantis, The Palm, Crescent Road, Dubai",
    menuName: "Nobu Classics",
    menuDescription: "Japanese-Peruvian fusion — sashimi, black cod, wagyu & signature cocktails",
    items: [
      { name: "Black Cod Miso", description: "Filet of black cod marinated in den miso for days, baked and broiled to perfection", price: "295", category: "Signature Dishes", isBestseller: true, isChefsPick: true },
      { name: "Yellowtail Jalapeño", description: "Sliced yellowtail sashimi with garlic, jalapeño and citrus soy", price: "145", category: "Cold Dishes", isBestseller: true },
      { name: "Tiradito Nobu Style", description: "Whitefish sashimi in chili-infused sesame oil with rocoto pepper", price: "135", category: "Cold Dishes" },
      { name: "Rock Shrimp Tempura", description: "Battered shrimp tossed in creamy spicy sauce with yuzu and shiitake", price: "155", category: "Hot Dishes" },
      { name: "Wagyu Beef Tacos", description: "Japanese wagyu in crispy taco shells with wasabi salsa", price: "185", category: "Hot Dishes" },
      { name: "Tuna Tataki Salad", description: "Rare grilled tuna sashimi with black pepper on field greens", price: "125", category: "Cold Dishes" },
      { name: "Grilled Chilean Sea Bass", description: "With dry miso and shiso salsa verde", price: "275", category: "From the Kitchen" },
      { name: "Wagyu Beef Toban Yaki", description: "Premium wagyu cooked on a hot stone plate with mushrooms", price: "350", category: "From the Kitchen", isChefsPick: true },
      { name: "Lobster Shiitake Salad", description: "Poached lobster with shiitake mushrooms and spicy lemon dressing", price: "195", category: "Cold Dishes" },
      { name: "New Style Salmon Sashimi", description: "Fresh salmon with hot olive oil, soy and ginger", price: "115", category: "Cold Dishes" },
      { name: "Shrimp and Lobster Ceviche", description: "With rocoto pepper, cilantro and lime", price: "165", category: "Cold Dishes" },
      { name: "Chicken Wings", description: "Crispy wings with spicy garlic sauce and shiso", price: "95", category: "Hot Dishes" },
      { name: "Bento Box", description: "Chef's daily selection of Nobu classics in a curated bento", price: "225", category: "From the Kitchen" },
      { name: "Nobu Sushi Platter", description: "Assorted premium nigiri and sashimi — chef's selection", price: "320", category: "Sushi" },
      { name: "Chocolate Bento Box", description: "Warm chocolate fondant with green tea ice cream", price: "85", category: "Desserts" },
    ],
  },
  {
    name: "La Petite Maison",
    slug: "la-petite-maison-dubai",
    cuisineType: "French-Mediterranean",
    description: "Acclaimed French-Mediterranean restaurant in DIFC, known for its Niçoise-inspired cuisine, vibrant atmosphere, and a menu that celebrates fresh, seasonal ingredients. A perennial favorite among Dubai's dining elite.",
    address: "Gate Village, DIFC, Dubai",
    menuName: "Déjeuner & Dîner",
    menuDescription: "Niçoise-inspired French Mediterranean — fresh salads, seafood & classic bistro fare",
    items: [
      { name: "Tuna Carpaccio", description: "Thinly sliced raw tuna with olive oil, lemon and capers", price: "125", category: "Starters", isBestseller: true },
      { name: "Burrata", description: "Creamy burrata with heirloom tomatoes, basil and aged balsamic", price: "110", category: "Starters", isChefsPick: true },
      { name: "Warm Prawns à la Plancha", description: "King prawns grilled with garlic butter and herbs de Provence", price: "145", category: "Starters" },
      { name: "Salade Niçoise LPM", description: "Classic Niçoise with seared tuna, green beans, olives and egg", price: "115", category: "Salads", isBestseller: true },
      { name: "Grilled Chicken Paillard", description: "Pounded and grilled free-range chicken with arugula and lemon", price: "155", category: "Main Courses" },
      { name: "Pan-Fried Sea Bass", description: "Mediterranean sea bass with crushed potatoes and olive tapenade", price: "225", category: "Main Courses", isChefsPick: true },
      { name: "Grilled Lamb Cutlets", description: "Herb-crusted lamb with ratatouille and rosemary jus", price: "245", category: "Main Courses" },
      { name: "Truffle Linguine", description: "Fresh pasta with black truffle, parmesan and butter sauce", price: "175", category: "Main Courses" },
      { name: "Beef Tenderloin", description: "Prime beef with pommes purée and red wine jus", price: "285", category: "Main Courses" },
      { name: "Tarte Tatin", description: "Classic French upside-down apple tart with crème fraîche", price: "75", category: "Desserts" },
      { name: "Crème Brûlée", description: "Vanilla bean crème brûlée with caramelized sugar", price: "65", category: "Desserts" },
    ],
  },
  {
    name: "Pierchic",
    slug: "pierchic-dubai",
    cuisineType: "Seafood",
    description: "One of Dubai's most romantic dining destinations, perched on its own pier extending into the Arabian Gulf. Pierchic serves premium seafood with stunning views of the Burj Al Arab and Madinat Jumeirah.",
    address: "Al Qasr, Madinat Jumeirah, Dubai",
    menuName: "Ocean to Table",
    menuDescription: "Premium seafood & ocean-to-table dining with Arabian Gulf views",
    items: [
      { name: "Oysters (Half Dozen)", description: "Freshly shucked oysters with shallot vinaigrette and lemon", price: "195", category: "Raw Bar", isBestseller: true },
      { name: "Lobster Bisque", description: "Rich and creamy lobster bisque with a touch of brandy", price: "95", category: "Starters" },
      { name: "Tuna Tartare", description: "Yellowfin tuna with avocado, sesame and ponzu", price: "135", category: "Starters", isChefsPick: true },
      { name: "King Crab Legs", description: "Steamed Alaskan king crab with drawn butter", price: "395", category: "Main Courses" },
      { name: "Grilled Whole Lobster", description: "Atlantic lobster grilled with herb butter, served with seasonal vegetables", price: "450", category: "Main Courses", isBestseller: true, isChefsPick: true },
      { name: "Pan-Seared Halibut", description: "With saffron risotto, asparagus and champagne beurre blanc", price: "275", category: "Main Courses" },
      { name: "Grilled Hammour", description: "Local hammour fillet with roasted vegetables and chermoula", price: "235", category: "Main Courses" },
      { name: "Seafood Platter for Two", description: "Lobster, king crab, prawns, oysters and grilled fish — served on ice", price: "750", category: "Sharing Platters" },
      { name: "Wagyu Beef Tenderloin", description: "For non-seafood lovers — prime wagyu with truffle jus", price: "345", category: "Main Courses" },
      { name: "Sticky Toffee Pudding", description: "Warm date cake with toffee sauce and vanilla ice cream", price: "75", category: "Desserts" },
      { name: "Chocolate Fondant", description: "Warm chocolate cake with a molten center and berries", price: "85", category: "Desserts" },
    ],
  },
  {
    name: "Tresind Studio",
    slug: "tresind-studio-dubai",
    cuisineType: "Indian Fine Dining",
    description: "With only 18 seats per night, Tresind Studio is Dubai's most exclusive Indian fine dining experience. Chef Himanshu Saini crafts an innovative multi-course tasting menu that reimagines Indian cuisine with modern techniques.",
    address: "DIFC, Dubai",
    menuName: "Tasting Menu",
    menuDescription: "18-seat chef's counter — innovative Indian tasting menu experience",
    items: [
      { name: "Golgappa Trio", description: "Three crispy puri filled with tamarind, mint and spiced water", price: "85", category: "Appetizers", isBestseller: true },
      { name: "Truffle Naan", description: "Wood-fired naan with black truffle butter and garlic", price: "75", category: "Breads" },
      { name: "Butter Chicken 2.0", description: "Reimagined butter chicken with tandoori spiced mousse", price: "165", category: "Signature Dishes", isBestseller: true, isChefsPick: true },
      { name: "Dal Makhani", description: "Slow-cooked 48-hour black lentils with cream and butter", price: "95", category: "Signature Dishes" },
      { name: "Lamb Rogan Josh", description: "Kashmiri-style braised lamb in aromatic spice gravy", price: "195", category: "Main Courses" },
      { name: "Prawn Moilee", description: "Kerala-style coconut curry with tiger prawns and curry leaves", price: "175", category: "Main Courses" },
      { name: "Tandoori Lobster", description: "Half lobster marinated in yogurt spices, roasted in tandoor", price: "295", category: "From the Tandoor", isChefsPick: true },
      { name: "Paneer Tikka", description: "Cottage cheese marinated in spiced yogurt, charcoal grilled", price: "85", category: "From the Tandoor" },
      { name: "Biryani Royale", description: "Slow-dum lamb biryani with saffron, rose and aged basmati", price: "185", category: "Rice" },
      { name: "Gulab Jamun Cheesecake", description: "Fusion dessert combining classic gulab jamun with New York cheesecake", price: "85", category: "Desserts" },
      { name: "Rasmalai Tres Leches", description: "Indian-inspired tres leches soaked in cardamom milk and saffron", price: "75", category: "Desserts" },
    ],
  },
  {
    name: "Nammos",
    slug: "nammos-dubai",
    cuisineType: "Greek-Mediterranean",
    description: "Inspired by the legendary Nammos Mykonos, this beach restaurant at the Four Seasons brings the spirit of the Greek isles to Dubai. Mediterranean cuisine, beachside dining, and vibrant summer energy year-round.",
    address: "Four Seasons Resort, Jumeirah Beach Road, Dubai",
    menuName: "Mediterranean Menu",
    menuDescription: "Greek-Mediterranean beach dining — fresh seafood, grills & shared plates",
    items: [
      { name: "Grilled Octopus", description: "Tender charcoal-grilled octopus with capers, olives and lemon", price: "145", category: "Starters", isBestseller: true, isChefsPick: true },
      { name: "Taramasalata", description: "Traditional creamy fish roe dip with warm pita", price: "65", category: "Mezze" },
      { name: "Tzatziki", description: "Greek yogurt with cucumber, garlic and fresh dill", price: "55", category: "Mezze" },
      { name: "Grilled Halloumi", description: "Cypriot halloumi cheese grilled until golden with honey and thyme", price: "85", category: "Starters" },
      { name: "Whole Grilled Sea Bream", description: "Fresh sea bream grilled with olive oil, lemon and oregano", price: "245", category: "Seafood", isChefsPick: true },
      { name: "Grilled Prawns", description: "Jumbo tiger prawns grilled with garlic butter and ouzo", price: "275", category: "Seafood" },
      { name: "Lamb Souvlaki", description: "Marinated lamb skewers with tzatziki and warm pita", price: "165", category: "Grills" },
      { name: "Chicken Gyros Plate", description: "Roasted chicken with tomato, onion, fries and yogurt sauce", price: "125", category: "Grills" },
      { name: "Moussaka", description: "Layers of eggplant, minced lamb, potato and béchamel", price: "135", category: "Main Courses", isBestseller: true },
      { name: "Greek Salad", description: "Tomatoes, cucumber, feta, olives, red onion and oregano dressing", price: "85", category: "Salads" },
      { name: "Baklava", description: "Layers of phyllo with pistachio and honey syrup", price: "55", category: "Desserts" },
      { name: "Greek Yogurt with Honey", description: "Thick yogurt with thyme honey and walnuts", price: "45", category: "Desserts" },
    ],
  },
  {
    name: "La Cantine du Faubourg",
    slug: "la-cantine-dubai",
    cuisineType: "French",
    description: "A chic Parisian brasserie transplanted to Dubai's Emirates Towers. Known for its buzzy atmosphere, stellar wine list, and refined French cuisine with international twists. The Saturday brunch is legendary.",
    address: "Jumeirah Emirates Towers, Sheikh Zayed Road, Dubai",
    menuName: "Le Menu",
    menuDescription: "Parisian brasserie — French classics, seafood & wood-fired specialties",
    items: [
      { name: "Tuna Ceviche", description: "Fresh tuna with passion fruit, chili and coriander", price: "115", category: "Starters", isBestseller: true },
      { name: "Truffle Cheese Pasta", description: "Les coquillettes de mon enfance — truffly, cheesy pasta dream", price: "145", category: "Starters", isChefsPick: true },
      { name: "Foie Gras Terrine", description: "With toasted brioche, fig chutney and fleur de sel", price: "165", category: "Starters" },
      { name: "Beef Short Ribs", description: "Honey-glazed short ribs slow-cooked for 12 hours", price: "225", category: "Main Courses", isBestseller: true, isChefsPick: true },
      { name: "Grilled Salmon", description: "Norwegian salmon with crushed potatoes and dill cream", price: "175", category: "Main Courses" },
      { name: "Duck Breast", description: "Pan-seared duck with cherry sauce and sweet potato purée", price: "195", category: "Main Courses" },
      { name: "Wagyu Burger", description: "Premium wagyu patty with truffle mayo, gruyère and caramelized onions", price: "145", category: "Main Courses" },
      { name: "Chicken Milanese", description: "Crispy breaded chicken with arugula and parmesan salad", price: "135", category: "Main Courses" },
      { name: "Caesar Salad", description: "Romaine hearts with anchovy dressing, croutons and aged parmesan", price: "85", category: "Salads" },
      { name: "Crème Brûlée", description: "Madagascar vanilla bean crème brûlée", price: "65", category: "Desserts" },
      { name: "Molten Chocolate Cake", description: "Warm Valrhona chocolate fondant with vanilla ice cream", price: "75", category: "Desserts" },
    ],
  },
  {
    name: "Al Nafoorah",
    slug: "al-nafoorah-dubai",
    cuisineType: "Lebanese",
    description: "One of Dubai's finest Lebanese restaurants, Al Nafoorah at Jumeirah Emirates Towers serves authentic Lebanese cuisine with a contemporary touch. Award-winning for its mezze, grills, and warm hospitality.",
    address: "Jumeirah Emirates Towers, Sheikh Zayed Road, Dubai",
    menuName: "Lebanese Classics",
    menuDescription: "Authentic Lebanese — mezze, mixed grills, fresh bread & traditional sweets",
    items: [
      { name: "Hummus", description: "Creamy chickpea dip with tahini, lemon and olive oil", price: "45", category: "Cold Mezze", isBestseller: true },
      { name: "Mutabal", description: "Smoky grilled eggplant dip with tahini and pomegranate", price: "45", category: "Cold Mezze" },
      { name: "Fattoush", description: "Crispy bread salad with mixed vegetables and pomegranate dressing", price: "55", category: "Salads", isBestseller: true },
      { name: "Lamb Kibbeh", description: "Deep-fried bulgur shells filled with spiced lamb and pine nuts", price: "65", category: "Hot Mezze", isChefsPick: true },
      { name: "Cheese Sambousek", description: "Crispy pastry filled with akkawi cheese and herbs", price: "55", category: "Hot Mezze" },
      { name: "Mixed Grill", description: "Lamb kofta, chicken tawook, lamb chops and beef kebab with rice", price: "195", category: "Grills", isBestseller: true, isChefsPick: true },
      { name: "Chicken Tawook", description: "Marinated chicken breast grilled on charcoal with garlic paste", price: "125", category: "Grills" },
      { name: "Lamb Chops", description: "Tender French-cut lamb chops seasoned and charcoal grilled", price: "175", category: "Grills" },
      { name: "Grilled Hammour", description: "Fresh local hammour fillet with tahini sauce", price: "155", category: "Seafood" },
      { name: "Chicken Shawarma Plate", description: "Thinly sliced roasted chicken with pickles, toum and fries", price: "95", category: "Main Courses" },
      { name: "Knafeh", description: "Warm cheese pastry with orange blossom syrup", price: "55", category: "Desserts" },
      { name: "Umm Ali", description: "Traditional Egyptian bread pudding with cream and nuts", price: "45", category: "Desserts" },
    ],
  },
  {
    name: "Dinner by Heston",
    slug: "dinner-by-heston-dubai",
    cuisineType: "British Fine Dining",
    description: "World-renowned chef Heston Blumenthal's restaurant at Atlantis The Royal. A theatrical fine dining experience with dishes inspired by historic British gastronomy, reimagined with modern techniques.",
    address: "Atlantis The Royal, Palm Jumeirah, Dubai",
    menuName: "Historic Menu",
    menuDescription: "Historic British cuisine reimagined — theatrical presentation & modern techniques",
    items: [
      { name: "Meat Fruit", description: "Chicken liver parfait shaped as a mandarin, served with toasted bread — Heston's iconic dish, c.1500", price: "125", category: "Starters", isBestseller: true, isChefsPick: true },
      { name: "Hay Smoked Mackerel", description: "With pickled lemon, smoked anchovy and rye bread, c.1670", price: "115", category: "Starters" },
      { name: "Rice and Flesh", description: "Saffron risotto with calf tail, bone marrow and red wine, c.1390", price: "175", category: "Main Courses" },
      { name: "Wagyu Beef Fillet", description: "Western Australian wagyu with mushroom ketchup and triple-cooked chips, c.1830", price: "395", category: "Main Courses", isChefsPick: true },
      { name: "Roast Halibut", description: "With smoked artichoke, pickled mushroom and cockle ketchup, c.1860", price: "295", category: "Main Courses" },
      { name: "Hereford Rib-Eye", description: "Dry-aged rib-eye with bone marrow sauce and watercress, c.1720", price: "345", category: "Main Courses" },
      { name: "Truffle Mash Potato", description: "Creamy mashed potato with shaved black truffle", price: "85", category: "Sides" },
      { name: "Triple-Cooked Chips", description: "Heston's legendary triple-cooked thick-cut chips", price: "65", category: "Sides", isBestseller: true },
      { name: "Tipsy Cake", description: "Spit-roasted pineapple with butterscotch sauce, c.1810", price: "95", category: "Desserts", isBestseller: true },
      { name: "Olive Oil Perfume", description: "Chocolate ganache with olive oil and rosemary — surprisingly delicious, c.1720", price: "85", category: "Desserts" },
    ],
  },
  {
    name: "SUSHISAMBA",
    slug: "sushisamba-dubai",
    cuisineType: "Japanese-Brazilian-Peruvian",
    description: "Perched on the 51st floor of The Palm Tower, SUSHISAMBA fuses Japanese, Brazilian and Peruvian cuisine with breathtaking 360-degree views. A vibrant dining experience combining world-class food with Dubai's most stunning panorama.",
    address: "The View at The Palm, Level 51, Palm Jumeirah, Dubai",
    menuName: "Fusion Menu",
    menuDescription: "Japanese-Brazilian-Peruvian fusion on the 51st floor — sushi, ceviche & robata",
    items: [
      { name: "Wagyu Gyoza", description: "Pan-seared wagyu beef dumplings with truffle ponzu", price: "125", category: "Small Plates", isBestseller: true },
      { name: "Yellowtail Tiradito", description: "Japanese yellowtail with rocoto tiger's milk and crispy garlic", price: "115", category: "Ceviche & Tiradito" },
      { name: "Salmon Ceviche", description: "Fresh salmon with aji amarillo, red onion and sweet potato", price: "105", category: "Ceviche & Tiradito", isChefsPick: true },
      { name: "Tuna Tataki", description: "Seared tuna with jalapeño, ponzu and garlic chips", price: "135", category: "Small Plates" },
      { name: "Robata Short Ribs", description: "Slow-cooked beef short ribs with anticucho glaze", price: "245", category: "Robata Grill", isBestseller: true, isChefsPick: true },
      { name: "Chilean Sea Bass", description: "Miso-marinated sea bass with shiso and ginger salsa", price: "275", category: "Robata Grill" },
      { name: "Dragon Roll", description: "Shrimp tempura topped with avocado, eel sauce and tobiko", price: "95", category: "Sushi Rolls" },
      { name: "SAMBA Roll", description: "Signature roll with spicy tuna, tempura flakes and mango", price: "110", category: "Sushi Rolls" },
      { name: "Wagyu Nigiri", description: "A5 wagyu beef nigiri with truffle soy and gold leaf", price: "145", category: "Nigiri" },
      { name: "Chicken Anticucho", description: "Peruvian-spiced grilled chicken skewers with aji panca", price: "95", category: "Robata Grill" },
      { name: "Passion Fruit Crème Brûlée", description: "Tropical twist on the classic with coconut tuile", price: "75", category: "Desserts" },
      { name: "Chocolate Bonsai Tree", description: "Edible dark chocolate sculpture with hazelnut praline", price: "95", category: "Desserts" },
    ],
  },
];
